#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/go/src/github.com/jddixon/xgo_go
  
  rm -rf template/tmp/* 
  
  pySloc -L go  -X mdZZZ -X *.pb.go -v $@
else
  echo "DEV_BASE is not defined"
fi
