#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/go/src/github.com/jddixon/xgo
  
  pushd cmd/xgoT
  go build && go install
  popd
  pushd cmd/xgoXPP
  go build && go install
  popd
  
else
  echo "DEV_BASE is not defined"
fi
