projConfig.toml for xgo_go

[meta]
    version = '0.1.0'

[project]
    name = 'xgo_go'  # distro name
    package = 'xgo_go'  # internal name
    main_lang = 'go'
    version = '0.2.3'
    version_date = '2017-05-20'
    author = 'Jim Dixon'
    author_email = 'jddixon@gmail.com'
    copyright = '2013-2016'
    description = 'needs a project description'
    dev_status = 'pre-alpha'
    license = 'mit'
    relpath = 'go/src/github.com/jddixon/xgo_go'
    state = 'shared'
    url = 'https://jddixon.github.io/xgo_go'

[go]
    cmds=['xgoXPP', 'xgoT']
